### ISSUE TITLE
Update Gemfile.lock to use current versions of gems 

### ISSUE THREAD

**Issue by elipousson** [p2pu/course-in-a-box#87]
I noticed that there are new versions of several of the gems listed in Gemfile.lock so I went through and updated the versions on [a fork I created](https://github.com/elipousson/course-in-a-box/blob/gh-pages/Gemfile.lock). If this is helpful (and I made the changes correctly), I'm happy to create a pull request.

I'm still pretty new to Jekyll and GitHub so I'm not sure the best way to do this – feel free to delete the issue if it isn't welcome or necessary.

**Comment by dirkcuys** [comment]
Hi @elipousson . Thanks for the contribution! I see that Jekyll 3 are now the default for GitHub pages!! I can't directly take a pull request from your repository since there are also other changes present: https://github.com/p2pu/course-in-a-box/compare/gh-pages...elipousson:gh-pages, but I'll update the Gemfile.lock. Thanks again!
